# -*- coding: utf-8 -*-
"""MDM_2_Search_Algorithms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lu6ao-Zs1qpRnSrAXsay4i4I8FSJF50m
"""

from collections import deque
import heapq
import time

graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': ['G'],
    'E': ['G'],
    'F': ['G'],
    'G': []
}

print("Graph:")
for node in graph:
    print(node, "->", graph[node])

from collections import deque

def bfs(graph, start):
    visited = set()
    queue = deque([start])

    print("BFS Traversal:")

    while queue:
        node = queue.popleft()

        if node not in visited:
            print(node, end=" ")
            visited.add(node)

            for neighbour in graph[node]:
                if neighbour not in visited:
                    queue.append(neighbour)

bfs(graph, 'A')

visited = set()

def dfs(graph, node):
    if node not in visited:
        print(node, end=" ")
        visited.add(node)

        for neighbour in graph[node]:
            dfs(graph, neighbour)

print("DFS Traversal:")
dfs(graph, 'A')

heuristic = {
    'A': 6,
    'B': 4,
    'C': 4,
    'D': 1,
    'E': 3,
    'F': 2,
    'G': 0
}

def best_first_search(graph, heuristic, start, goal):
    visited = set()
    priority_queue = [(heuristic[start], start)]

    print("Best First Search:")

    while priority_queue:
        h, node = heapq.heappop(priority_queue)

        if node in visited:
            continue

        print(node, end=" ")
        visited.add(node)

        if node == goal:
            break

        for neighbour in graph[node]:
            if neighbour not in visited:
                heapq.heappush(
                    priority_queue,
                    (heuristic[neighbour], neighbour)
                )

best_first_search(graph, heuristic, 'A', 'G')

weighted_graph = {
    'A': [('B', 2), ('C', 3)],
    'B': [('D', 4), ('E', 2)],
    'C': [('F', 3)],
    'D': [('G', 1)],
    'E': [('G', 3)],
    'F': [('G', 2)],
    'G': []
}

def a_star(graph, heuristic, start, goal):
    priority_queue = [(heuristic[start], 0, start, [start])]
    visited = set()

    while priority_queue:
        f, cost, node, path = heapq.heappop(priority_queue)

        if node in visited:
            continue

        visited.add(node)

        if node == goal:
            print("A* Path:", path)
            print("Path Cost:", cost)
            return

        for neighbour, edge_cost in graph[node]:

            if neighbour not in visited:
                new_cost = cost + edge_cost
                new_f = new_cost + heuristic[neighbour]

                heapq.heappush(
                    priority_queue,
                    (new_f, new_cost, neighbour, path + [neighbour])
                )

a_star(weighted_graph, heuristic, 'A', 'G')

# Hill Climbing Algorithm

def hill_climbing():
    current = 0

    values = [1, 3, 5, 7, 6, 4, 2]

    while True:
        left = current - 1
        right = current + 1

        best = current

        if left >= 0 and values[left] > values[best]:
            best = left

        if right < len(values) and values[right] > values[best]:
            best = right

        if best == current:
            break

        current = best

    print("Maximum Value:", values[current])
    print("Position:", current)


hill_climbing()

# Map Coloring using Constraint Satisfaction Problem

# Regions and their neighboring regions
neighbors = {
    'A': ['B', 'C'],
    'B': ['A', 'C', 'D'],
    'C': ['A', 'B', 'D'],
    'D': ['B', 'C']
}

# Available colors
colors = ['Red', 'Green', 'Blue']

# Store the color assigned to each region
assignment = {}


def is_safe(region, color):
    for neighbor in neighbors[region]:
        if neighbor in assignment and assignment[neighbor] == color:
            return False
    return True


def solve(regions):
    if not regions:
        return True

    region = regions[0]

    for color in colors:
        if is_safe(region, color):
            assignment[region] = color

            if solve(regions[1:]):
                return True

            del assignment[region]

    return False


# Solve the CSP
regions = list(neighbors.keys())

if solve(regions):
    print("Map Coloring Solution:")
    for region in regions:
        print(region, "=", assignment[region])
else:
    print("No solution found")